version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: marcoroth
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/Zurich
  open-pull-requests-limit: 10
  target-branch: development
  assignees:
  - marcoroth
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: minitest
    versions:
    - 5.14.3
  registries:
  - git-github-com
