Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Layout/LineLength:
  Max: 180

Metrics/BlockLength:
  Max: 100

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Metrics/AbcSize:
  Max: 200

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true
